import json
import logging
import os
import requests
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - NarratorAgent - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class NarratorAgent:
    """
    NarratorAgent - The Storyteller of StreamSentinel
    
    After every incident, this agent writes a plain English
    post-mortem report combining everything:
    - What was detected
    - What the AI diagnosed
    - How bad it was
    - What was done about it
    
    Think of it like a journalist who watched the whole
    incident and writes the story the moment it's over.
    No human needed. No 3am writing sessions.
    """
    
    def __init__(self):
        self.ollama_url = "http://localhost:11434/api/generate"
        self.model = "llama3.2"
        self.reports_dir = "logs/incident_reports"
        self.reports = []
        
        # Create reports directory if it doesn't exist
        os.makedirs(self.reports_dir, exist_ok=True)
        logger.info("NarratorAgent initialized")
        logger.info(f"📁 Reports will be saved to: {self.reports_dir}")
    
    def build_narrative_prompt(
        self,
        anomaly: dict,
        diagnosis: dict,
        blast_assessment: dict,
        remediation: dict
    ) -> str:
        """
        Build a prompt that gives the AI the full picture
        of what happened during this incident.
        """
        return f"""You are a senior site reliability engineer writing 
an incident post-mortem report. Write in clear, plain English.
Be concise but complete. No jargon without explanation.

INCIDENT SUMMARY:
=================
Anomaly Detected: {anomaly.get('type', 'UNKNOWN')}
Severity: {anomaly.get('severity', 'UNKNOWN')}
Topic: {anomaly.get('topic', 'UNKNOWN')}
Time Detected: {anomaly.get('timestamp', 'UNKNOWN')}
Details: {anomaly.get('message', 'No details')}

AI DIAGNOSIS:
=============
{diagnosis.get('ai_diagnosis', 'No diagnosis available')}

BLAST RADIUS ASSESSMENT:
========================
Blast Radius: {blast_assessment.get('blast_radius', 'UNKNOWN')}
Affected Services: {blast_assessment.get('affected_services', [])}
High Criticality Services: {blast_assessment.get('high_criticality_services', [])}

REMEDIATION TAKEN:
==================
Action: {remediation.get('action', 'UNKNOWN')}
Fix Applied: {remediation.get('fix_applied', 'None')}
Team Notified: {remediation.get('notified_team', False)}
Resolved At: {remediation.get('timestamp', 'UNKNOWN')}

Please write a post-mortem report with these sections:
1. INCIDENT TITLE: One clear sentence describing what happened
2. TIMELINE: Key events with approximate times
3. WHAT HAPPENED: Plain English explanation (2-3 sentences max)
4. IMPACT: Who and what was affected
5. HOW IT WAS RESOLVED: What was done
6. LESSONS LEARNED: One actionable takeaway
7. PREVENTION: One specific thing to prevent recurrence

Keep the whole report under 300 words.
Write like you're explaining to a smart non-engineer."""

    def ask_ai(self, prompt: str) -> str:
        """Send the full incident context to AI for narration"""
        try:
            logger.info("✍️ NarratorAgent writing incident report...")
            
            response = requests.post(
                self.ollama_url,
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False
                },
                timeout=120
            )
            
            if response.status_code == 200:
                return response.json().get("response", "No response")
            else:
                return f"AI unavailable: {response.status_code}"
                
        except Exception as e:
            logger.error(f"Failed to reach AI: {e}")
            return "Narrative generation unavailable"
    
    def save_report(self, report: dict):
        """Save the report to a markdown file"""
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        filename = f"{self.reports_dir}/incident_{timestamp}.md"
        
        with open(filename, 'w') as f:
            f.write(f"# Incident Report\n\n")
            f.write(f"**Generated by:** StreamSentinel NarratorAgent\n")
            f.write(f"**Time:** {report['timestamp']}\n")
            f.write(f"**Anomaly:** {report['anomaly_type']}\n")
            f.write(f"**Blast Radius:** {report['blast_radius']}\n\n")
            f.write(f"---\n\n")
            f.write(report['narrative'])
        
        logger.info(f"📄 Report saved to: {filename}")
        return filename
    
    def narrate(
        self,
        anomaly: dict,
        diagnosis: dict,
        blast_assessment: dict,
        remediation: dict
    ) -> dict:
        """
        Main method — takes all incident data and writes
        a complete post-mortem report automatically.
        """
        logger.info("📰 NarratorAgent starting incident narration...")
        
        # Build the prompt with full context
        prompt = self.build_narrative_prompt(
            anomaly, diagnosis, blast_assessment, remediation
        )
        
        # Ask AI to write the narrative
        narrative = self.ask_ai(prompt)
        
        # Package the report
        report = {
            "anomaly_type": anomaly.get("type"),
            "blast_radius": blast_assessment.get("blast_radius"),
            "timestamp": datetime.utcnow().isoformat(),
            "narrative": narrative,
            "generated_by": "NarratorAgent-Llama3.2"
        }
        
        self.reports.append(report)
        
        # Save to file
        filename = self.save_report(report)
        
        # Print the narrative
        logger.info(
            f"\n{'='*60}\n"
            f"📰 INCIDENT POST-MORTEM REPORT\n"
            f"{'='*60}\n"
            f"{narrative}\n"
            f"{'='*60}\n"
            f"✅ Report saved to: {filename}"
        )
        
        return report


if __name__ == "__main__":
    from blast_radius_agent import BlastRadiusAgent
    from remediation_agent import RemediationAgent
    
    print("Testing NarratorAgent with a full incident simulation...\n")
    
    # Simulate a full incident
    test_anomaly = {
        "type": "LARGE_TRANSACTION",
        "severity": "MEDIUM",
        "message": "Unusually large transaction: $750,000 USD",
        "timestamp": datetime.utcnow().isoformat(),
        "topic": "financial-transactions"
    }
    
    test_diagnosis = {
        "ai_diagnosis": """
        ROOT CAUSE: Misconfigured payment gateway allowing 
        transactions above normal thresholds.
        
        BUSINESS IMPACT: Potential regulatory exposure and 
        unauthorized fund movement risk.
        
        IMMEDIATE ACTION: Freeze the transaction, alert 
        compliance team, investigate source account.
        
        PREVENTION: Implement transaction amount limits with 
        dual approval for amounts over $100,000.
        """
    }
    
    blast_agent = BlastRadiusAgent()
    test_blast = blast_agent.calculate_blast_radius(
        "financial-transactions", 
        "LARGE_TRANSACTION"
    )
    
    remediation_agent = RemediationAgent()
    test_remediation = remediation_agent.remediate(
        test_anomaly, 
        test_blast
    )
    
    narrator = NarratorAgent()
    report = narrator.narrate(
        test_anomaly,
        test_diagnosis,
        test_blast,
        test_remediation
    )
    
    print(f"\n✅ NarratorAgent test complete!")
    print(f"Total reports generated: {len(narrator.reports)}")